# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(216, 100)
        self.citiesButton = QtWidgets.QPushButton(Dialog)
        self.citiesButton.setGeometry(QtCore.QRect(30, 20, 75, 23))
        self.citiesButton.setObjectName("citiesButton")
        self.sexsButton = QtWidgets.QPushButton(Dialog)
        self.sexsButton.setGeometry(QtCore.QRect(110, 20, 75, 23))
        self.sexsButton.setObjectName("sexsButton")
        self.countriesButton = QtWidgets.QPushButton(Dialog)
        self.countriesButton.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.countriesButton.setObjectName("countriesButton")
        self.agesButton = QtWidgets.QPushButton(Dialog)
        self.agesButton.setGeometry(QtCore.QRect(110, 50, 75, 23))
        self.agesButton.setObjectName("agesButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.citiesButton.setText(_translate("Dialog", "Город"))
        self.sexsButton.setText(_translate("Dialog", "Пол"))
        self.countriesButton.setText(_translate("Dialog", "Стран"))
        self.agesButton.setText(_translate("Dialog", "Возраст"))
